---
title: "The first satRdays conference in New Zealand"
slug: satrdays-nz
tags:
- R
- conference
categories: Post
---

*27 February 2020*  

The first [satrdays conference](https://satrdays.org/) was held in Auckland, New Zealand on 22 February 2020. We had an amazing day pulled together by a great group of volunteers and we hope that we can hold this event annually, and perhaps in cities around New Zealand.

```{r, eval=TRUE}
blogdown::shortcode("twitter", "1231039366438387713")
```

This blog covers:

- the motivation behind running the event  
- the organisation process behind the scenes  
- the speakers
- the conference stats  
- some of the takeaways  

# Motivation for a satRdays conference in New Zealand

I was inspired to "throw" a [satRdays](https://satrdays.org/) conference in New Zealand after speaking to the [Steph Locke](https://twitter.com/thestephlocke) after she presented a workshop at [R-Ladies Auckland](https://twitter.com/rladiesakl). In New Zealand we didn't yet have a data science related community conference that bridged and connected academia and industry.  This event also seemed like a good complement to the existing R-Ladies meetup to promote gender diversity in the R community. I come from a self taught, slightly non-traditional data science background, so I personally wanted to see more people, especially underrepresented groups, feel confident to learn R and share this knowledge within a community. 


# The process of organising this event

When it came to organising the event we ran lean, remotely and sometimes we were just winging it. [Earo Wang](https://twitter.com/earowang) joined me as a co-organiser after a quick chat an R-Ladies event. She was in the process of moving cities from Melbourne to Auckland to join the Statistics Department at the University and arrived 16 days days before the conference. We didn't have a fully fledged committee and we only did things that we thought needed to be done first time round, rather than doing all the things on a potential conference wish list. 

In the early stages of organising the conference, [Thomas Lumley](https://twitter.com/tslumley) arranged a free venue at the [Statistics Department at the University of Auckland](https://twitter.com/statsauckuni). This enabled us to lock in a date in the satRdays global calendar and kick started the momentum for the event. We wanted to set up a conference with community and open source values from the outset. We sent requests to [RStudio](https://rstudio.com/about/) and [RConsortium](https://www.r-consortium.org/projects/r-user-group-support-program), both of whom have sponsored other satRdays, for financial sponsorship. 

We landed on what we hoped was a reasonable $60 ticket price. With this budget, we could then provide free tickets to the volunteers, a number of students and the speakers and so provide coffees, morning and afternoon tea cookies and a brown bag lunch for all attendees. The catering set up outside the room was intentional to facilitate networking and conversations at the intervals.

We chose not to use lanyards as name tags (as Earo had a large collection already!) and used plastic name tags with a clip and pin for different clothing types. We could then collect the name tags and reuse them across future meetup groups and conferences.

My brother, [Neil Fitter](https://uk.linkedin.com/in/neilfitter) redesigned the generic satRday logo with fern and a [koru](https://en.wikipedia.org/wiki/Koru). This design was done just in time to get printed hex stickers, which were the only conference swag.  We did however print T-shirts with the new logo, for the volunteers at the event, to help attendees identify volunteers.

During the sessions, we chose to use www.sli.do for the speakers to moderate the Q&A. We hoped that this would engage the audience and inspire quieter voices to have a shared platform with the more confident question askers. 

## The speakers at the event

One of the main differences between other satRdays and our conference is the geographical location of New Zealand.  Our budget was very small and did not extend to cover any travel costs of international speakers. However we were very fortunate to have [JJ Allaire](https://twitter.com/fly_upside_down), the founder of RStudio perform the keynote, **Open Source Software for Data Science**, while he was on a family holiday in New Zealand.

We set a limit of 200 attendees because that that was the limit of the room booking and since we had one room we had a single track of sequential speakers. We wanted to attract a variety of attendees so we set up four sessions applications of R, graphics, teaching and Production/Infrastructure, each session proceeded with a local invited speaker. 

For the applications of R we invited [Jacquie Tran](https://twitter.com/jacquietran) who spoke about **Data practices and data problems in performance sport**.

For graphics we invited [Harkanwal Singh](https://twitter.com/kamal_hothi) who presented **The craft of data storytelling**.

The teaching session was invited speaker, [Anna Fergusson](https://twitter.com/annafergussonnz), talking about **Five ways to make learnr even better for teaching**.

Then the production/infrastructure invited speaker was [Simon Urbanek](https://urbanek.info/) talking about **Scalable Collaborative Data Science using R**.

We then set up a Sessionize link to call for speakers to either submit contributed talks or lightning talks.  It was interesting to see how lightning talks, that seem like a seemingly easy introduction to speaking, were very under subscribed.


Profiles of the speakers and the schedule are available on the [website](https://auckland2020.satrdays.org/).

The videos are available on [YouTube](https://www.youtube.com/playlist?list=PL8ncIDIP_e6v1dV1xVacsH4qjuoPMMnDe), with a huge thanks to [Jonathan Ng](https://www.linkedin.com/in/jonathanjng/).

## Event measures of success

We succeeded in throwing a conference and we have some conference statistics for 2020:

+ 1 keynote
+ 4 invited speakers
+ 5 lightning talks
+ 10 contributed talks
+ 70 attendees and 100% turn out
+ 5 free student tickets, and free tickets for speakers and volunteers
+ 1 free intro to R mini workshop on the Friday
+ Conference ticket full price $60

However the impact of these events are often intangible. Once we have facilitated the event, on the actual event date it is the attendees that make the conference in terms of presentation content, networking or opportunities that unfold.
  
## Organiser takeaways

Finally there are some our takeaways from the first satRdays conference:

+ Diversity is an ongoing effort in a community, and while gender diversity is important, it is a wider issue that needs thought and consideration.  
+ We already have amazing and inspiring speakers in the R community but communication is an essential skill for anyone who works with data.  We need to promote,  encouraging and mentor new speakers to apply for all speaking opportunities so that we keep the pool of speakers growing.

If you were there, we are thrilled to have had you involved and would like to hear what you thought, so send us an [email](satrday.auckland@gmail.com). Otherwise if you would like to join us next year then keep an eye on our [satRday New Zealand twitter](https://twitter.com/SatRday_NZ).

